// <auto-generated />
using System;
using Architect.DddEfDemo.DddEfDemo.Infrastructure.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Architect.DddEfDemo.DddEfDemo.Infrastructure.Databases.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_100_BIN2")
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Architect.DddEfDemo.DddEfDemo.Domain.Parties.Seller", b =>
                {
                    b.Property<decimal>("Id")
                        .HasPrecision(28)
                        .HasColumnType("decimal(28,0)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<DateTime>("ModificationDateTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("ModificationDateTime");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Architect.DddEfDemo.DddEfDemo.Domain.Products.Product", b =>
                {
                    b.Property<decimal>("Id")
                        .HasPrecision(28)
                        .HasColumnType("decimal(28,0)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("ModificationDateTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("ModificationDateTime");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            CreationDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModificationDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Product One"
                        },
                        new
                        {
                            Id = 2m,
                            CreationDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModificationDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Product Two"
                        });
                });

            modelBuilder.Entity("Architect.DddEfDemo.DddEfDemo.Domain.Quotations.Quotation", b =>
                {
                    b.Property<decimal>("Id")
                        .HasPrecision(28)
                        .HasColumnType("decimal(28,0)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("ExpirationDateTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Lines")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SellerId")
                        .HasPrecision(28)
                        .HasColumnType("decimal(28,0)");

                    b.HasKey("Id");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("ExpirationDateTime");

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("Architect.DddEfDemo.DddEfDemo.Domain.Products.Product", b =>
                {
                    b.OwnsOne("Architect.DddEfDemo.DddEfDemo.Domain.Products.ManufacturerDetails", "Manufacturer", b1 =>
                        {
                            b1.Property<decimal>("ProductId")
                                .HasPrecision(28)
                                .HasColumnType("decimal(28,0)");

                            b1.Property<int>("EstablishedYear")
                                .HasColumnType("int")
                                .HasColumnName("ManufacturerEst");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("ManufacturerName")
                                .UseCollation("Latin1_General_100_CI_AS");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.HasData(
                                new
                                {
                                    ProductId = 1m,
                                    EstablishedYear = 1970,
                                    Name = "Bob the Builder"
                                });
                        });

                    b.Navigation("Manufacturer");
                });
#pragma warning restore 612, 618
        }
    }
}
